// User Login
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const SET_BROWSER_ID = "SET_BROWSER_ID";

// Reset Password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const USER_REFRESH_RESET_PASSWORD = "USER_REFRESH_RESET_PASSWORD";

// Societies

export const GET_ALL_SOCIETIES_REQUEST = "GET_ALL_SOCIETIES_REQUEST";
export const GET_ALL_SOCIETIES_SUCCESS = "GET_ALL_SOCIETIES_SUCCESS";
export const GET_ALL_SOCIETIES_FAIL = "GET_ALL_SOCIETIES_FAIL";

// PHASES

export const GET_ALL_PHASES_REQUEST = "GET_ALL_PHASES_REQUEST";
export const GET_ALL_PHASES_SUCCESS = "GET_ALL_PHASES_SUCCESS";
export const GET_ALL_PHASES_FAIL = "GET_ALL_PHASES_FAIL";


// BLOCKS

export const GET_ALL_BLOCKS_REQUEST = "GET_ALL_BLOCKS_REQUEST";
export const GET_ALL_BLOCKS_SUCCESS = "GET_ALL_BLOCKS_SUCCESS";
export const GET_ALL_BLOCKS_FAIL = "GET_ALL_BLOCKS_FAIL";
